### PR TITLE
Reduce performance impact of reading history.

### LINKED ISSUE #133: `$&sethistory` is slow (with readline)
Pretty much the title.  My `.es-history` has hit some 50,000 lines now, and it seems to have slowed down starting up _es_ from ~3-5ms to ~70-90ms, which has become noticeable.  It also, naturally, eats quite a bit of memory.

What's worse (and what got me actually looking into this) is that slowdown (and extra memory usage) also affects non-interactive shell scripts.  Even the zero-byte script takes extra tens of milliseconds (and extra megabytes of RAM) to run with a large `$history` file, which isn't even used!

Perhaps it would be useful to delay calling `read_history()` until the first `callreadline()`; perhaps `stifle_history()` could be a smaller number (perhaps it could be a user-supplied number?); perhaps other shells like bash are doing something extra-clever that we could crib.

I've also noticed that _re_-setting history takes even longer.
```
; time {history = $history}
     0r     0.3u     0.0s	{history=$history}
```

### LINKED ISSUE #135: `$&sethistory` with no arguments still reads a history file
While looking at #133, i noticed that `$&sethistory` with no arguments (i.e. an empty list) results in calling `read_history(NULL)`, which results in reading `~/.history`.

There are some problems with this:

1. History will be loaded from that file, but new command lines won't be saved to it because `history = ()` still results in `$history` being an empty list.
2. `read_history(NULL)` does not consider `HOME` when the manual mentions `~/.history`; it instead relies entirely on `getpwent()` or whatever for tilde expansion.
3. `~/.history` is the default history file used by tcsh with a default timestamp format that includes a sign (i.e. `#{+|-}nnn`) while `read_history()` uses `#nnn` only, making them incompatible.
   Setting `history_comment_char = '#';` in `initinput()` doesn't change anything by itself &mdash; the tcsh timestamps are treated like normal shell comments that look like `#+1729429672`, which included in the history list.
   Removing the leading `+` (or `-`) character from all timestamps in the file makes `read_history()` correctly avoid loading the timestamped lines as shell comments, but the next execution of tcsh just ignores what it thinks are invalid timestamps in the history file and rewrites the commands to the file with new timestamps in the tcsh format.

Given all of these issues, i'm not sure `read_history()` should be called at all if `$&sethistory` was provided no arguments, making it effectively a no-op other than returning an empty list.

### PR DESCRIPTION
**Pull request by jpco**
1. Do not do so unless actually necessary (that is, either when we call `callreadline()` or when we change the value again later).
2. Shrink stifle_history size to 5000.

Both of these speed up startup quite a bit, and both also reduce memory usage quite a bit as well.  The first one is an unambiguous win; the second may be unfortunate for those folks who want to search some very old commands.  Does anyone want a `$max-history-size` variable so as to have a choice in the matter?

Also, I'll repeat my question from the linked issue: Should we clear the in-memory history when $history is changed?

This fixes #133 (edit: it also fixes #135).

### CODE REVIEW

**Review by wryun — APPROVED** [review]
Works for me. I would probably set the default slightly higher (I like having lots of history available for searching), but I probably should just figure out how to use atuin.

**Comment by wryun** [comment]
(and yes, I would vote to clear the history when changed, just to avoid confusion)

**Comment by jpco** [comment]
`clear_history()` is in there now.  I've also added `$max-history-length`, which you and I can set to different values according to our preferences.

**Comment by jpco** [comment]
Okay.  Un-did the automatic history clearing, but made it so `max-history-length = 0` clears the history (and `set-history` can temporarily set `max-history-length = 0` if desired).  If @memreflect likes it, I think this covers everything in #133.

This PR also fixes #135 now by skipping calls to `read_history(NULL)`.

**Comment by jpco** [comment]
Oh wow: This PR speeds up `make test` on my machine from 1.810 seconds to 0.26 seconds, a reduction of 86%.  That's how much time _es_ has been wasting on just loading up `~/.es-history` each time it started up a new non-interactive binary.  Testing a relatively short, quick (but real) script in `valgrind` also shows a 98% reduction in bytes-in-use at exit and a 99.8% reduction in total bytes allocated.

**Pull request merged**
