### PR TITLE
Use POSIX-compatible setpgid()

### PR DESCRIPTION
**Pull request by jpco**
This PR is stuff that's a bit difficult to reason about, since outside of job control, process group related changes are basically only visible through side effects.  This description describes the state for all POSIX-compliant OSes (in particular, those with `setsid()`.)

State before:
 - The `$&newpgrp` primitive places _es_ into its own session, and attempts to take the terminal for the new process group implicitly created with the new session, which always quietly fails.
 - If built with `JOB_PROTECT`, then _es_ places every new background process into a new session.  This causes certain "shell-spawning" processes like terminals and window managers to fail to kill those backgrounded processes when they exit.  This can be useful, but is nonstandard and often undesirable.

State after:
 - The `$&newpgrp` primitive places _es_ into a new process group and attempts to take the terminal, which (usually) succeeds, and _es_ complains if it doesn't.
 - If built with `JOB_PROTECT`, then _es_ places every new background process into a new process group, _if_ _es_ is interactive.  In this case backgrounded processes stay alive on terminal exit.  In non-interactive scenarios, background processes stay in the same pgroup as the shell, which can be managed as, well, a group.
 - If built with `JOB_PROTECT`, then _es_ attempts to put itself in the foreground after each `wait()`. This is to avoid accidentally getting stopped by the `SIGT*` signals, which usually ends up taking down the whole terminal.
 - If built with `JOB_PROTECT`, then _es_ "returns" the terminal to its previous foreground process group on exit, if relevant.  This is to avoid the case where an _es_ invoked by a non-pgroup-aware parent process causes that parent to be stopped by a `SIGT*` signal, which also usually takes down the whole terminal.

This is all in the vague direction of job control, but the intent is only to achieve the following three goals: 1. don't remove features that already exist (`$&newpgrp` and background processes in separate pgroups), 2. do so in a standards-compliant way (that is, using `setpgid` to actually create new process groups), and 3. maintain "sanity" (as in, don't kill terminals at surprising times) by default.  There's a little more complex behavior in this PR than I'd like, but I also think it's the minimal set of behavior to achieve these three things.

The overall high-level impact of this change is that forked processes will be stopped and killed more than they were before.  I think the new cases of stoppage and killage are more "correct", since the rest of the OS "expects" a process group/session structure like this in how it interacts with shells.  Some users may be disturbed that certain background processes exit at different times than they used to, however.  There should be no meaningful change for the `-DJOB_PROTECT=0` case.

Alternatives to the design proposed here include:
 - Using the `$&newpgrp` primitive, and maybe a new `$&newsession` primitive, to manage how backgrounding works, instead of compile-time flags.  Doing this with `$&newpgrp` is like half-way to my job control proposal (#84) so I hesitate to suggest that here, though.  And I don't have a good idea whether a `$&newsession` primitive is really very useful -- maybe the few users who really want new sessions can use the `setsid` binary?
 - Maintaining "sanity" through primitives in the shell rather than within the C runtime.  Personally, I think of terminal process group management in the same category as automatically reaping processes that have been `wait()`ed for, or managing opening/closing file descriptors -- it's almost certainly better to just let the shell runtime do it.

### CODE REVIEW

**Comment by memreflect** [comment]
I'm not sure if it was intentional or not, but i noticed `$&newpgrp` steals the terminal whether built with `JOB_PROTECT` or not, yet the terminal process group is only restored upon exit if built with `JOB_PROTECT`, resulting in the terminal disappearing.

That's the only potential issue i see; this PR looks good otherwise.
It's well-considered, and it doesn't sacrifice existing functionality, unlike more radical alternatives such as dropping `$&newpgrp` to avoid the process group issue entirely.

You could use `ctermid()` to determine the path to the controlling terminal and obtain a file descriptor for use with `tcsetpgrp()`.
If `ctermid()` returns a null pointer or an empty string, or `eopen()` fails, then fall back to assuming the controlling terminal is on file descriptor 2 and hope for the best.
That's the only improvement i can suggest.

> This is all in the vague direction of job control, but the intent is only to achieve the following three goals: 1. don't remove features that already exist (`$&newpgrp` and background processes in separate pgroups), 2. do so in a standards-compliant way (that is, using `setpgid` to actually create new process groups), and 3. maintain "sanity" (as in, don't kill terminals at surprising times) by default. There's a little more complex behavior in this PR than I'd like, but I also think it's the minimal set of behavior to achieve these three things.

From what i can tell, you have accomplished those goals as i haven't found any cases that caused trouble aside from the one i already mentioned about `JOB_PROTECT`.
Considering the added complication that the combination of `setpgid()` and `tcsetpgrp()` brings, this does appear to be quite minimal.

> Alternatives to the design proposed here include:
> 
> * Using the `$&newpgrp` primitive, and maybe a new `$&newsession` primitive, to manage how backgrounding works, instead of compile-time flags.  Doing this with `$&newpgrp` is like half-way to my job control proposal ([A new design for the old monster: job control #84](https://github.com/wryun/es-shell/discussions/84)) so I hesitate to suggest that here, though.  And I don't have a good idea whether a `$&newsession` primitive is really very useful -- maybe the few users who really want new sessions can use the `setsid` binary?

When would you use `$&newsession` instead of `$&newpgrp` and vice versa?
Would there be enough of a difference to warrant the two different primitives?

> * Maintaining "sanity" through primitives in the shell rather than within the C runtime.  Personally, I think of terminal process group management in the same category as automatically reaping processes that have been `wait()`ed for, or managing opening/closing file descriptors -- it's almost certainly better to just let the shell runtime do it.

Sure, primitives called in just the right place(s) might work, but all it takes is someone overriding a hook or another function to cause trouble when they omit the necessary primitives.
By keeping things in the C code, the shell's initialization and termination code in C will prevent it from interfering with other programs, like a shell without job control that doesn't restore the terminal process group after a wait.

**Comment by jpco** [comment]
> I'm not sure if it was intentional or not, but i noticed `$&newpgrp` steals the terminal whether built with `JOB_PROTECT` or not, yet the terminal process group is only restored upon exit if built with `JOB_PROTECT`, resulting in the terminal disappearing.

It is intentional, but basically only to maintain precedent (Modulo the `setsid` thing, but if modern POSIX `setsid` was really the intended behavior then the `tcsetpgrp` wouldn't have made any sense to add, so I believe this maintains the _intended_ precedent.)  I don't have a very good intuition of the hypothetical use case for compiling without `JOB_PROTECT` but also using `$&newpgrp`, so precedent is all I really have to fall back on.

> You could use ctermid() to determine the path to the controlling terminal and obtain a file descriptor for use with tcsetpgrp().

That's a good point, this isn't maximally robust to stderr shenanigans.  Actually, bash seems to have a nice logical flow for this; they check `isatty(2)` and if that's true, they use an fd from `dup(2)`, and if false, fall back to a fd from `open("/dev/tty")`.  I'm not sure the `dup` would be necessary for _es_ with its fd-protection scheme.  I'm also not sure what the difference materially is between using `"/dev/tty"` vs. `ctermid()`.  I'm also not practically sure how to trigger any issues with the current less-robust scheme, and I'd love to figure out a test case to prove the fix.

All this to say, I like it, but preferably in a later PR.  I think there will probably a fair bit of careful massaging that will need be done with this logic for corners-of-corner-cases.  After all, every shell that knows anything about process groups has a fun little rat's nest of logic around this exact thing, and the user-driven control flow of _es_ makes it even worse.

**Comment by memreflect** [comment]
> It is intentional, but basically only to maintain precedent (Modulo the `setsid` thing, but if modern POSIX `setsid` was really the intended behavior then the `tcsetpgrp` wouldn't have made any sense to add, so I believe this maintains the _intended_ precedent.) I don't have a very good intuition of the hypothetical use case for compiling without `JOB_PROTECT` but also using `$&newpgrp`, so precedent is all I really have to fall back on.

Fair enough.
I'm also unsure how the shell should behave without job control, especially when POSIX requires that implementations support job control...
Managing terminal access in a job control shell is simple in theory.
For a shell without job control, however, it appears to get quite troublesome with signals and different processes wanting to do I/O.
That's unfortunately necessary if `$&newpgrp` is going to stick around.

> That's a good point, this isn't maximally robust to stderr shenanigans. Actually, bash seems to have a nice logical flow for this; they check `isatty(2)` and if that's true, they use an fd from `dup(2)`, and if false, fall back to a fd from `open("/dev/tty")`. I'm not sure the `dup` would be necessary for _es_ with its fd-protection scheme. I'm also not sure what the difference materially is between using `"/dev/tty"` vs. `ctermid()`.

POSIX requires `"/dev/tty"` to refer to the controlling terminal for compatibility with historical usage, so please ignore my rambling about `ctermid()`.
Until someone complains that `"/dev/tty"` doesn't work on their system, i see no reason to prefer `ctermid()`.
As for the `dup()` idea, i honestly haven't investigated enough to comment on that, but it sounds nice in theory.

> I'm also not practically sure how to trigger any issues with the current less-robust scheme, and I'd love to figure out a test case to prove the fix.

Start an _es_ with fd 2 redirected to a file, then execute `newpgrp`.
`tcsetpgrp()` fails with `ENOTTY` after `setpgid()` succeeds, so the shell is now executing in the foreground as part of a background process group.

After some investigation, i found the shell will hang on `SIGTTOU` if readline is enabled, hang on `SIGTTIN` (readline: only when `SIGTTOU` is ignored), or simply die if both are ignored; `JOB_PROTECT` doesn't matter.

It might be a good idea to have `$&newpgrp` reverse the effects of `setpgid(0, 0)` if `tcsetpgrp()` fails, then complain using `fail()`.
That would prevent the shell from hanging and/or dying.

**Comment by jpco** [comment]
> Start an _es_ with fd 2 redirected to a file, then execute newpgrp. `tcsetpgrp()` fails with `ENOTTY` after `setpgid()` succeeds, so the shell is now executing in the foreground as part of a background process group.

Aha, yup, got it:
```
; {./es -c 'newpgrp; echo sigttou; echo sigttin on <=%read'} >[2] err.log
```
(which line it gets stopped on depends on the state of `tostop` in `stty`.)  The bash-like logic mentioned earlier fixes it. I found that the `dup()` call protects the shell in case `exec {>[2] file}` is run mid-shell execution, so it's going in, too.

> It might be a good idea to have `$&newpgrp` reverse the effects of `setpgid(0, 0)` if `tcsetpgrp()` fails, then complain using `fail()`.

I think I agree. `$&newpgrp` isn't meant to put the shell in the background, and doing so is almost certainly trouble.  Better to handle it and throw an exception than to quietly do the wrong, and likely to explode, thing.

**Comment by memreflect** [comment]
* `newpgrp()` is effectively equivalent to `spgrp(getpid())`, so are both `newpgrp()` and `spgrp()` necessary?
* `tctakepgrp()` and `tcspgrp()` both return either -1 with a non-zero `errno` or 0.
  Since 0 means "no error" for both the return value and `errno`, you could simply return 0 or an `errno` value like `ENOTTY` directly.
  Some younger interfaces such as `posix_spawn()` and `pthread_create()` do that already, so it's not unprecedented.
* There are a few inconsistencies in how `ttyfd==0` is handled.
  Sometimes it leads to `ENOTTY` while it is treated as a valid file descriptor at other times.

* If you start _es_ with the `-o` flag when any of the file descriptors 0, 1, or 2 are inherited closed, then the value of `ttyfd` will be the lowest of those, despite being closed intentionally:

  ```
  ; es.ttyfd -o -c 'echo you typed: <= %read' <[0=]
  {%close 0 {es.ttyfd -o -c 'echo you typed: <= %read'}}
  DEBUG: ttyfd=0
  fox
  you typed: fox

  ; es.ttyfd -o -c 'echo you typed: <= %read' >[1=]
  {%close 1 {es.ttyfd -o -c 'echo you typed: <= %read'}}
  DEBUG: ttyfd=1
  fox
  you typed: fox
  ```

  You can fix the bug easily enough:

  ```c
  /* don't forget to `#define REQUIRE_FCNTL 1` before including headers */

  #define MIN_ttyfd 3

  if (isatty(2))
    ttyfd = fcntl(2, F_DUPFD, MIN_ttyfd);
  else {
    ttyfd = opentty();
    if (0 <= ttyfd && ttyfd < MIN_ttyfd) {
      int fd = ttyfd;
      ttyfd = fcntl(fd, F_DUPFD, MIN_ttyfd);
      close(fd);
    }
  }
  assert(ttyfd < 0 || ttyfd >= MIN_ttyfd);
  ```

**Comment by jpco** [comment]
Good notes all.  Especially with `-o`, I certainly wouldn't have caught that.

**Pull request merged**
